# Generated by Django 5.2.12 on 2026-04-10 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Succursale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant', models.IntegerField()),
                ('devise', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('piece_identite', models.FileField(upload_to='pieces/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('destination', models.CharField(max_length=100)),
                ('heure_depart', models.DateTimeField(null=True)),
                ('heure_arrivee', models.DateTimeField(null=True)),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_expediteur', to='app.client')),
                ('recepteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_recepteur', to='app.client')),
                ('succursale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.succursale')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('devise', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('date_paiement', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.client')),
                ('coli', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.colis')),
            ],
        ),
    ]
