# Generated by Django 5.2.12 on 2026-04-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='colis',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='colis',
            name='est_valider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colis',
            name='etat',
            field=models.CharField(choices=[('traitement', 'En traitement'), ('voyage', 'En voyage'), ('arrive', 'Arrivée'), ('annule', 'Annulé')], default='traitement', max_length=100),
        ),
    ]
