# Generated by Django 5.2.12 on 2026-04-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_code_colis_code_colis_est_valider_colis_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lieu_naissance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
